name: Vanity Executor Bot

on:
  workflow_dispatch: # Allows you to start it manually from the Actions tab

jobs:
  execute:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Gives you 6 hours to interact via Telegram
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Executor Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          TRONGRID_API_KEY: ${{ secrets.TRONGRID_API_KEY }}
        run: python executor.py
